import { TabWidget } from "std-widgets.slint";


export component AppWindow inherits Window {
    width: 200px;
    height: 200px;
    in-out property <[{t:string, c: color}]> tabs: [
        { t:"First", c: #555 },
        { t:"Second", c: #aaa },
    ];
    in-out property <int> current_index: 0;

    VerticalLayout {
        width: 100%;
        height: 100%;
        // 自定义 Tab 栏
        Rectangle {
            background: #e5e5e5;
            HorizontalLayout {
                height: 36px;
                padding-top: 4px;
                padding-bottom: 4px;

                for tab[idx] in root.tabs: HorizontalLayout {
                    alignment: center;

                    bar := Rectangle {
                        background: oldlace;
                        width: root.width / tabs.length - 1px;
                        TouchArea {
                            clicked => {
                                root.current_index = idx;
                            }
                            Text {
                                text: tab.t;
                            }
                        }

                        Rectangle {
                            x: parent.x + parent.width - self.width - 2px;
                            y: parent.y + parent.height - parent.height / 2 - self.width / 2;
                            width: 10px;
                            height: 10px;
                            border-radius: 5px;
                            background: olivedrab;
                            border-color: olivedrab;
                            border-width: 1px;
                            TouchArea {
                                clicked => {
                                    bar.background = #a5a5a5;
                                }
                                Text {
                                    text: "x";
                                }
                            }
                        }
                    }

                    if idx < tabs.length: Rectangle {
                        width: 1px;
                        background: red;
                    }
                }
            }
        }

        // 内容区域
        Rectangle {
            width: 100%;   // 填充父容器宽度
            height: 100%; // 显式设置内容区域高度
            background: tabs[current_index].c;
        }
    }
}
